- name: Set tools
  set_fact:
    tools:
      - name: EarlyBird
        repo: 'https://github.com/americanexpress/earlybird.git'
        build: "./build.sh && ./install.sh"
      - name: Ripgrep
        install: "apt-get install -y ripgrep"
      - name: Gau-Expose
        repo: 'https://github.com/tamimhasan404/Gau-Expose.git'
      - name: Mantra
        install: "/usr/local/go/bin/go install github.com/MrEmpy/mantra@latest"
        src: "{{ ansible_env.HOME }}/go/bin/mantra"
        dest: "/usr/local/bin/mantra"

- name: Ensure sensitive_finding directory exists
  file:
    path: "/opt/tools/sensitive_finding"
    state: directory
  become: yes

- name: Clone {{ item.name }} repository
  git:
    repo: "{{ item.repo | default(omit) }}"
    dest: "/opt/tools/sensitive_finding/{{ item.name }}"
  become: yes
  when: item.repo is defined
  loop: "{{ tools }}"

- name: Build and install {{ item.name }}
  shell: "cd /opt/tools/sensitive_finding/{{ item.name }}/ && {{ item.build }}"
  become: yes
  when: item.build is defined
  loop: "{{ tools }}"

- name: Install {{ item.name }}
  command: "{{ item.install | default(omit) }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes
  when: item.install is defined
  loop: "{{ tools }}"

- name: Copy {{ item.name }} binary to /usr/local/bin
  become: yes
  copy:
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    mode: "0755"
  when: item.src is defined and item.dest is defined
  loop: "{{ tools }}"

# - name: Ensure sensitive_finding directory exists
#   file:
#     path: "/opt/tools/sensitive_finding"
#     state: directory
#   become: yes


# - name: Clone EarlyBird repository
#   git:
#     repo: 'https://github.com/americanexpress/earlybird.git'
#     dest: /opt/tools/sensitive_finding/earlybird

# - name: Build and install EarlyBird
#   shell: "cd /opt/tools/sensitive_finding/earlybird && ./build.sh && ./install.sh"
#   args:
#     chdir: /opt/tools/sensitive_finding/earlybird

# - name: Install Ripgrep
#   apt:
#     name: ripgrep
#     state: present

# - name: Clone Gau-Expose repository
#   git:
#     repo: 'https://github.com/tamimhasan404/Gau-Expose.git'
#     dest: /opt/tools/sensitive_finding/Gau-Expose


# - name: Install Mantra
#   command: "/usr/local/go/bin/go install github.com/MrEmpy/mantra@latest"
#   environment:
#     GOPATH: "{{ ansible_env.HOME }}/go"
#     GOROOT: "/usr/local/go"
#     PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
#   become: yes

# - name: Copy mantra binary to /usr/local/bin
#   become: yes
#   copy:
#     src: "{{ ansible_env.HOME }}/go/bin/mantra"
#     dest: "/usr/local/bin/mantra"
#     mode: "0755"