- name: Install all tools
  hosts: local
  become: yes
  roles:
    - api
    - apt-gem-stuff
    - cms_scanner
    - configure-logging
    - configure-system
    - configure-tmux-vim
    - content_discovery
    - customize-browser
    - customize-terminal
    - directory_fuzzers
    - dns_resolver
    # - exploitation
    - frameworks
    - git_hunting
    - http_parameter
    - http_probe
    - inspecting_js
    - js_hunting
    - lfi_tools
    # - network_scanner
    - open_redirect
    - request_smuggling
    - sensitive_finding
    - sql_tools
    - ssrf_tools
    - subdomain_enum
    - ssti_tools
    - useful_tools
    - visual_tools
    - web_crawling
    - web_technologies
    - wordlists
    - xss_tools


    # - network_sacanner
    # - http_parameter 
    # - subdomain_enum
    # - visual_tools
    # - http_probe
    # - web_crawling
    # - apt-gem-stuff
    # - api
    # - content_discovery
    # - exploitation
    # - frameworks
    # - inspecting_js
    # - wordlists
    # - other
    # - directory_fuzzers
    #  - lfi_tools 
    #  - open_redirect
    # - ssrf_tools 
    # - ssti_tools 
    # - xss_tools 
    # - sql_tools 
    # - useful_tools
    # - sensitive_finding
    # - web_technologies 
    #   - cms_scanner
    # - git_hunting
    # - js_hunting
    # - dns_resolver
    # - configure-tmux
    # - request_smuggling 
