- name: Install all tools
  hosts: local
  become: yes
  roles:
    # - network_sacanner
    # - http_parameter 
    # - subdomain_enum
    # - visual_tools
    # - http_probe
    # - web_crawling
    # - common
    # - api
    # - content_discovery
    # - exploitation
    # - frameworks
    # - inspecting_js
    # - wordlists
    # - other
    # - directory_fuzzers
    #  - lfi_tools 
    #  - open_redirect
    # - ssrf_tools 
    # - ssti_tools 
    # - xss_tools 
    # - sql_tools 
    # - useful_tools
    # - sensitive_finding
    # - web_technologies 
      # - cms_scanner
    # - git_hunting
    # - js_hunting
    - dns_resolver
    # - request_smuggling 
