- name: Install Httpx
  command: "/usr/local/go/bin/go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes

- name: Copy Httpx binary to /usr/local/bin
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/go/bin/httpx"
    dest: "/usr/local/bin/httpx"
    mode: "0755"
  

- name: Install Httprobe
  command: "/usr/local/go/bin/go install -v github.com/tomnomnom/httprobe@latest"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes

- name: Copy Httprobe binary to /usr/local/bin
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/go/bin/httprobe"
    dest: "/usr/local/bin/httprobe"
    mode: "0755"