- name: Set xss_tools
  set_fact:
    xss_tools:
      - name: Dalfox
        install: "/usr/local/go/bin/go install github.com/hahwul/dalfox/v2@latest"
        src: "{{ ansible_env.HOME }}/go/bin/dalfox"
        dest: "/usr/local/bin/dalfox"
      - name: kxss
        install: "/usr/local/go/bin/go install github.com/Emoe/kxss@latest"
        src: "{{ ansible_env.HOME }}/go/bin/kxss"
        dest: "/usr/local/bin/kxss"
      - name: Gxssgo
        install: "/usr/local/go/bin/go install github.com/KathanP19/Gxss@latest"
        src: "{{ ansible_env.HOME }}/go/bin/Gxss"
        dest: "/usr/local/bin/Gxss"
      - name: Bxss
        install: "/usr/local/go/bin/go install github.com/ethicalhackingplayground/bxss@latest"
        src: "{{ ansible_env.HOME }}/go/bin/bxss"
        dest: "/usr/local/bin/bxss"
      - name: knoxnl
        install: "pip install knoxnl --break-system-packages"
      - name: Findom-xss
        install: "cd /opt/tools/xss_tools && git clone https://github.com/dwisiswant0/findom-xss.git > /dev/null 2>&1 && cd findom-xss && chmod +x findom-xss.sh && rm -rf LinkFinder && git clone https://github.com/GerbenJavado/LinkFinder.git > /dev/null 2>&1"
      - name: XSStrike
        repo: 'https://github.com/s0md3v/XSStrike'
        dest: /opt/tools/xss_tools/XSStrike
        requirements: "/opt/tools/xss_tools/XSStrike/requirements.txt"
      - name: XSS_VIBES
        repo: 'https://github.com/faiyazahmad07/xss_vibes.git'
        dest: /opt/tools/xss_tools/xss_vibes
        requirements: "/opt/tools/xss_tools/xss_vibes/requirements"

- name: Ensure xss_tools directory exists
  file:
    path: "/opt/tools/xss_tools"
    state: directory
  become: yes

- name: Clone {{ item.name }} repository
  git:
    repo: "{{ item.repo | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
  become: yes
  when: item.repo is defined
  loop: "{{ xss_tools }}"

- name: Install {{ item.name }}
  command: "{{ item.install | default(omit) }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes
  when: item.install is defined
  loop: "{{ xss_tools }}"

- name: Copy {{ item.name }} binary to /usr/local/bin
  become: yes
  copy:
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    mode: "0755"
  when: item.src is defined and item.dest is defined
  loop: "{{ xss_tools }}"

- name: Install requirements for {{ item.name }}
  shell: "pip3 install -r {{ item.requirements }} --break-system-packages"
  become: yes
  when: item.requirements is defined
  loop: "{{ xss_tools }}"
