- name: Set web_crawling_tools
  set_fact:
    web_crawling_tools:
      - name: Gospider
        install: "/usr/local/go/bin/go install github.com/jaeles-project/gospider@latest"
        src: "{{ ansible_env.HOME }}/go/bin/gospider"
        dest: "/usr/local/bin/gospider"
      - name: Hakrawler
        install: "/usr/local/go/bin/go install github.com/hakluke/hakrawler@latest"
        src: "{{ ansible_env.HOME }}/go/bin/hakrawler"
        dest: "/usr/local/bin/hakrawler"
      - name: Waybackurls
        install: "/usr/local/go/bin/go install github.com/tomnomnom/waybackurls@latest"
        src: "{{ ansible_env.HOME }}/go/bin/waybackurls"
        dest: "/usr/local/bin/waybackurls"
      - name: katana
        install: "/usr/local/go/bin/go install github.com/projectdiscovery/katana/cmd/katana@latest"
        src: "{{ ansible_env.HOME }}/go/bin/katana"
        dest: "/usr/local/bin/katana"
      - name: Parameters
        install: "/usr/local/go/bin/go install github.com/mrco24/parameters@latest"
        src: "{{ ansible_env.HOME }}/go/bin/parameters"
        dest: "/usr/local/bin/parameters"
      - name: GF
        install: "/usr/local/go/bin/go install github.com/tomnomnom/gf@latest"
        src: "{{ ansible_env.HOME }}/go/bin/gf"
        dest: "/usr/local/bin/gf"
      - name: otx-url
        install: "/usr/local/go/bin/go install github.com/mrco24/otx-url@latest"
        src: "{{ ansible_env.HOME }}/go/bin/otx-url"
        dest: "/usr/local/bin/otx-url"
      - name: Web-archive
        install: "/usr/local/go/bin/go install github.com/mrco24/web-archive@latest"
        src: "{{ ansible_env.HOME }}/go/bin/web-archive"
        dest: "/usr/local/bin/web-archive"
      - name: xnLinkFinder
        install: "/usr/bin/python3.11 -m pip install xnLinkFinder --break-system-packages"
      - name: ParamSpider
        repo: 'https://github.com/devanshbatham/paramspider'
        dest: /opt/tools/web_crawling/paramspider
        requirements: "/opt/tools/web_crawling/paramspider/env"
      - name: Guaplus
        repo: 'https://github.com/bp0lr/gauplus.git'
        dest: /opt/tools/web_crawling/gauplus
        build: "cd /opt/tools/web_crawling/gauplus && go build "
        src: "/opt/tools/web_crawling/gauplus/gauplus"
        bin_dest: "/usr/local/bin/gauplus"
      - name: freq
        repo: 'https://github.com/takshal/freq.git'
        dest: /opt/tools/web_crawling/freq
        build: "cd /opt/tools/web_crawling/freq/ && mv main.go freq.go && go build freq.go && cp freq /usr/bin"

- name: Ensure web_crawling directory exists
  file:
    path: "/opt/tools/web_crawling"
    state: directory
  become: yes

- name: Clone {{ item.name }} repository
  git:
    repo: "{{ item.repo | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
  become: yes
  when: item.repo is defined
  loop: "{{ web_crawling_tools }}"

- name: Install {{ item.name }}
  command: "{{ item.install | default(omit) }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes
  when: item.install is defined
  loop: "{{ web_crawling_tools }}"

- name: Copy {{ item.name }} binary to /usr/local/bin
  become: yes
  copy:
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    mode: "0755"
  when: item.src is defined and item.dest is defined
  loop: "{{ web_crawling_tools }}"

- name: Install requirements for {{ item.name }}
  shell: "pip3 install -r {{ item.requirements }} --break-system-packages"
  become: yes
  when: item.requirements is defined
  loop: "{{ web_crawling_tools }}"

- name: Build {{ item.name }}
  shell: "{{ item.build | default(omit) }}"
  become: yes
  when: item.build is defined
  loop: "{{ web_crawling_tools }}"