- name: Set ssrf_tools
  set_fact:
    ssrf_tools:
      - name: Interactsh
        install: "/usr/local/go/bin/go install github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest"
        src: "{{ ansible_env.HOME }}/go/bin/interactsh-client"
        dest: "/usr/local/bin/interactsh-client"
      - name: SSRFmap
        repo: 'https://github.com/swisskyrepo/SSRFmap'
        install: "cd /opt/tools/ssrf_tools/SSRFmap && pip3 install -r requirements.txt --break-system-packages"
      - name: Gopherus
        repo: 'https://github.com/tarunkant/Gopherus.git'
        install: "cd /opt/tools/ssrf_tools/Gopherus && chmod +x install.sh && ./install.sh"

- name: Ensure ssrf_tools directory exists
  file:
    path: "/opt/tools/ssrf_tools"
    state: directory
  become: yes

- name: Clone {{ item.name }} repository
  git:
    repo: "{{ item.repo | default(omit) }}"
    dest: "/opt/tools/ssrf_tools/{{ item.name }}"
  become: yes
  when: item.repo is defined
  loop: "{{ ssrf_tools }}"

- name: Install {{ item.name }}
  command: "{{ item.install | default(omit) }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes
  when: item.install is defined
  loop: "{{ ssrf_tools }}"

- name: Copy {{ item.name }} binary to /usr/local/bin
  become: yes
  copy:
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    mode: "0755"
  when: item.src is defined and item.dest is defined
  loop: "{{ ssrf_tools }}"
  
# - name: Ensure ssrf_tools directory exists
#   file:
#     path: "/opt/tools/ssrf_tools"
#     state: directory
#   become: yes



# - name: Install Interactsh
#   command: "/usr/local/go/bin/go install github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest"
#   environment:
#     GOPATH: "{{ ansible_env.HOME }}/go"
#     GOROOT: "/usr/local/go"
#     PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
#   become: yes

# - name: Copy Interactsh binary to /usr/local/bin
#   become: yes
#   copy:
#     src: "{{ ansible_env.HOME }}/go/bin/interactsh-client"
#     dest: "/usr/local/bin/interactsh-client"
#     mode: "0755"


# - name: Install SSRFmap using git
#   git:
#     repo: 'https://github.com/swisskyrepo/SSRFmap'
#     dest: /opt/tools/ssrf_tools/SSRFmap
#   become: yes


# - name: Install requirements for SSRFmap
#   shell: "cd /opt/tools/ssrf_tools/SSRFmap && pip3 install -r requirements.txt --break-system-packages"
#   become: yes


# - name: Install Gopherus using git
#   git:
#     repo: 'https://github.com/tarunkant/Gopherus.git'
#     dest: /opt/tools/ssrf_tools/Gopherus
#   become: yes


# - name: Install requirements for Gopherus
#   shell: "cd /opt/tools/ssrf_tools/Gopherus && chmod +x install.sh && ./install.sh"
#   become: yes