---
- name: Include vars of blue_vars.yml file.
  include_vars:
    file: blue_vars.yml

- name: Update all packages to latest version
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install foremost, exiftool, steghide
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items: "{{ packages }}"

- name: Clone forensic tools.
  git:
    repo: "{{ item }}"
    dest: "{{ blue_dir }}{{ item.split('/')[-1].replace('.git','') }}"
    version: stable
    force: yes
  with_items: "{{ forensic_tools }}"
  become: yes

- name: Install volatility 3 requirements
  pip:
    requirements: "{{ blue_dir }}{{ vol3_dir }}/requirements.txt"

- name: Install olevba via pip for analyzing macros
  pip:
    name: "{{ item }}"
  with_items: "{{ pip_modules }}"
  become: yes

- name: Download oledump
  get_url:
    url: "http://didierstevens.com/files/software/oledump_V{{ oledump_version }}.zip"
    dest: "{{ blue_dir }}"
    checksum: "{{ oledump_checksum }}"

- name: Expand oledump
  unarchive:
    src: "{{ blue_dir }}oledump_V{{ oledump_version }}.zip"
    dest: "{{ oledump_dir }}"
    remote_src: yes

- name: Removing oledump zip
  file:
    path: "{{ blue_dir }}oledump_V{{ oledump_version }}.zip"
    state: absent
  become: yes

- name: Add forensic tools alias to .zshrc
  lineinfile:
    path: ~/.zshrc
    line: "{{ item }}"
  with_items: "{{ alias_items }}"
