- name: Ensure ssrf_tools directory exists
  file:
    path: "/opt/tools/ssrf_tools"
    state: directory
  become: yes



- name: Install Interactsh
  command: "/usr/local/go/bin/go install github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes

- name: Copy Interactsh binary to /usr/local/bin
  become: yes
  copy:
    src: "{{ ansible_env.HOME }}/go/bin/interactsh-client"
    dest: "/usr/local/bin/interactsh-client"
    mode: "0755"


- name: Install SSRFmap using git
  git:
    repo: 'https://github.com/swisskyrepo/SSRFmap'
    dest: /opt/tools/ssrf_tools/SSRFmap
  become: yes


- name: Install requirements for SSRFmap
  shell: "cd /opt/tools/ssrf_tools/SSRFmap && pip3 install -r requirements.txt --break-system-packages"
  become: yes


- name: Install Gopherus using git
  git:
    repo: 'https://github.com/tarunkant/Gopherus.git'
    dest: /opt/tools/ssrf_tools/Gopherus
  become: yes


- name: Install requirements for Gopherus
  shell: "cd /opt/tools/ssrf_tools/Gopherus && chmod +x install.sh && ./install.sh"
  become: yes