- name: Ensure web_technologies directory exists
  file:
    path: "/opt/tools/web_technologies"
    state: directory
  become: yes


- name: Install wappalyzer-cli
  shell: |
    cd /opt/tools/web_technologies &&
    git clone https://github.com/gokulapap/wappalyzer-cli &&
    cd wappalyzer-cli &&
    pip3 install . --break-system-packages;
  args:
    executable: /bin/bash