- name: Set tools
  ignore_errors: yes
  set_fact:
    tools:
      - name: EarlyBird
        repo: 'https://github.com/americanexpress/earlybird.git'
        build: "./build.sh && ./install.sh"
      - name: Ripgrep
        install: "apt-get install -y ripgrep"
      - name: Gau-Expose
        repo: 'https://github.com/tamimhasan404/Gau-Expose.git'
      - name: Mantra
        install: "/usr/local/go/bin/go install github.com/MrEmpy/mantra@latest"
        src: "{{ ansible_env.HOME }}/go/bin/mantra"
        dest: "/usr/local/bin/mantra"

- name: Ensure sensitive_finding directory exists
  ignore_errors: yes
  file:
    path: "/opt/tools/sensitive_finding"
    state: directory
  become: yes

- name: Clone {{ item.name }} repository
  ignore_errors: yes
  git:
    repo: "{{ item.repo | default(omit) }}"
    dest: "/opt/tools/sensitive_finding/{{ item.name }}"
  become: yes
  when: item.repo is defined
  loop: "{{ tools }}"

- name: Build and install {{ item.name }}
  ignore_errors: yes
  shell: "cd /opt/tools/sensitive_finding/{{ item.name }}/ && {{ item.build }}"
  become: yes
  when: item.build is defined
  loop: "{{ tools }}"

- name: Install {{ item.name }}
  ignore_errors: yes
  command: "{{ item.install | default(omit) }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes
  when: item.install is defined
  loop: "{{ tools }}"

- name: Copy {{ item.name }} binary to /usr/local/bin
  ignore_errors: yes
  become: yes
  copy:
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    mode: "0755"
  when: item.src is defined and item.dest is defined
  loop: "{{ tools }}"