- name: Ensure visual_tools directory exists
  ansible.builtin.file:
    path: "/opt/tools/visual_tools"
    state: directory
  become: yes

- name: Install Gowitness
  ansible.builtin.command:
    cmd: "/usr/local/go/bin/go install github.com/sensepost/gowitness@latest"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes

- name: Copy Gowitness binary to /usr/local/bin
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/go/bin/gowitness"
    dest: "/usr/local/bin/gowitness"
    mode: "0755"
  become: yes

- name: Download Aquatone
  ansible.builtin.get_url:
    url: "https://github.com/michenriksen/aquatone/releases/download/v1.7.0/aquatone_linux_amd64_1.7.0.zip"
    dest: "/tmp/aquatone_linux_amd64_1.7.0.zip"
  become: yes

- name: Ensure temporary directory for Aquatone exists
  ansible.builtin.file:
    path: "/tmp/aquatone"
    state: directory
  become: yes

- name: Extract Aquatone
  ansible.builtin.unarchive:
    src: "/tmp/aquatone_linux_amd64_1.7.0.zip"
    dest: "/tmp/aquatone"
    remote_src: yes
  become: yes

- name: Copy Aquatone binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/aquatone/aquatone"
    dest: "/usr/local/bin/aquatone"
    mode: "0755"
  become: yes
