- name: Ensure Firefox extensions directory exists
  become: yes
  file:
    path: "{{ lookup('env', 'HOME') }}/.mozilla/firefox/{{ firefox_profile }}/extensions"
    state: directory

- name: Download Firefox Extensions
  get_url:
    url: "{{ item.url }}"
    dest: "{{ lookup('env', 'HOME') }}/Downloads/{{ item.name | lower }}.xpi"
  become: yes
  with_items:
    - { name: "Hackbar", url: "https://addons.mozilla.org/firefox/downloads/latest/hackbar/addon-67890-latest.xpi" }
    - { name: "TWP", url: "https://addons.mozilla.org/firefox/downloads/file/4245500/traduzir_paginas_web-10.0.1.1.xpi" }
    - { name: "Shodan", url: "https://addons.mozilla.org/firefox/downloads/file/4117305/shodan_addon-1.1.1.xpi" }
    - { name: "Foxyproxy", url: "https://addons.mozilla.org/firefox/downloads/file/4228675/foxyproxy_basic-8.9.xpi" }
    - { name: "Trufflehog", url: "https://addons.mozilla.org/firefox/downloads/file/4035826/trufflehog-0.0.1.xpi" }
    - { name: "knoxss_community_edition", url: "https://addons.mozilla.org/firefox/downloads/file/3378216/knoxss_community_edition-0.2.0.xpi" }
    - { name: "dotgit", url: "https://addons.mozilla.org/firefox/downloads/file/4169848/dotgit-4.8.xpi" }
    - { name: "modheader", url: "https://addons.mozilla.org/firefox/downloads/file/4161194/modheader_firefox-4.4.1.xpi" }
    - { name: "HackTools", url: "https://addons.mozilla.org/firefox/downloads/file/3901885/hacktools-0.4.0.xpi" }
    - { name: "open_multiple_urls", url: "https://addons.mozilla.org/firefox/downloads/file/4201128/open_multiple_urls-1.6.0.xpi" }
    - { name: "Cookie-Editor", url: "https://addons.mozilla.org/firefox/downloads/file/4241002/cookie_editor-1.13.0.xpi" }
    - { name: "vulners_web_scanner", url: "https://addons.mozilla.org/firefox/downloads/file/817904/vulners_web_scanner-1.0.6.xpi" }
    - { name: "retire_js", url: "https://addons.mozilla.org/firefox/downloads/file/4250269/retire_js-2.0.0.xpi" }
    - { name: "darkreader", url: "https://addons.mozilla.org/firefox/downloads/file/4249607/darkreader-4.9.80.xpi" }

- name: Move downloaded extensions to Firefox profile extensions directory
  become: yes
  command: "cp {{ lookup('env', 'HOME') }}/Downloads/{{ item.name | lower }}.xpi {{ lookup('env', 'HOME') }}/.mozilla/firefox/{{ firefox_profile }}/extensions"
  with_items:
    - { name: "Hackbar" }
    - { name: "TWP" }
    - { name: "Shodan" }
    - { name: "Foxyproxy" }
    - { name: "Trufflehog" }
    - { name: "knoxss_community_edition" }
    - { name: "dotgit" }
    - { name: "modheader" }
    - { name: "HackTools" }
    - { name: "open_multiple_urls" }
    - { name: "Cookie-Editor" }
    - { name: "vulners_web_scanner" }
    - { name: "retire_js" }
    - { name: "darkreader" }
