- name: Set sql_tools
  ignore_errors: yes
  set_fact:
    sql_tools:
      - name: Jeeves
        install: "/usr/local/go/bin/go install github.com/ferreiraklet/Jeeves@latest"
        src: "{{ ansible_env.HOME }}/go/bin/Jeeves"
        dest: "/usr/local/bin/Jeeves"
      - name: time-sql
        install: "/usr/local/go/bin/go install github.com/mrco24/time-sql@latest"
        src: "{{ ansible_env.HOME }}/go/bin/time-sql"
        dest: "/usr/local/bin/time-sql"
      - name: mrco24-error-sql
        install: "/usr/local/go/bin/go install github.com/mrco24/mrco24-error-sql@latest"
        src: "{{ ansible_env.HOME }}/go/bin/mrco24-error-sql"
        dest: "/usr/local/bin/mrco24-error-sql"
      - name: ghauri
        repo: 'https://github.com/r0oth3x49/ghauri.git'
        install: "cd /opt/tools/sql_tools/ghauri && python3 -m pip install --upgrade -r requirements.txt --break-system-packages && python3 setup.py install"

- name: Ensure sql_tools directory exists
  ignore_errors: yes
  file:
    path: "/opt/tools/sql_tools"
    state: directory
  become: yes

- name: Clone {{ item.name }} repository
  ignore_errors: yes
  git:
    repo: "{{ item.repo | default(omit) }}"
    dest: "/opt/tools/sql_tools/{{ item.name }}"
  become: yes
  when: item.repo is defined
  loop: "{{ sql_tools }}"

- name: Install {{ item.name }}
  ignore_errors: yes
  command: "{{ item.install | default(omit) }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes
  when: item.install is defined
  loop: "{{ sql_tools }}"

- name: Copy {{ item.name }} binary to /usr/local/bin
  ignore_errors: yes
  become: yes
  copy:
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    mode: "0755"
  when: item.src is defined and item.dest is defined
  loop: "{{ sql_tools }}"
