- name: Set tools
  set_fact:
    tools:
      - name: Getjs
        install: "/usr/local/go/bin/go install github.com/003random/getJS@latest"
        src: "{{ ansible_env.HOME }}/go/bin/getJS"
        dest: "/usr/local/bin/getJS"
      - name: LinkFinder
        repo: 'https://github.com/GerbenJavado/LinkFinder.git'
        requirements: "pip3 install -r requirements.txt --break-system-packages"
      - name: SecretFinder
        repo: 'https://github.com/m4ll0k/SecretFinder.git'
        requirements: "pip3 install -r requirements.txt --break-system-packages && pip3 install jsbeautifier --break-system-packages && pip3 install lxml --break-system-packages"
      - name: JSScanner
        repo: 'https://github.com/dark-warlord14/JSScanner'
        requirements: "bash install.sh"

- name: Ensure js_hunting directory exists
  file:
    path: "/opt/tools/js_hunting"
    state: directory
  become: yes

- name: Install {{ item.name }}
  command: "{{ item.install | default(omit) }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOROOT: "/usr/local/go"
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin:{{ ansible_env.HOME }}/go/bin"
  become: yes
  when: item.install is defined
  loop: "{{ tools }}"

- name: Copy {{ item.name }} binary to /usr/local/bin
  become: yes
  copy:
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest | default(omit) }}"
    mode: "0755"
  when: item.src is defined and item.dest is defined
  loop: "{{ tools }}"

- name: Install {{ item.name }} using git
  git:
    repo: "{{ item.repo | default(omit) }}"
    dest: "/opt/tools/js_hunting/{{ item.name }}"
  become: yes
  when: item.repo is defined
  loop: "{{ tools }}"

- name: Install requirements for {{ item.name }}
  shell: "cd /opt/tools/js_hunting/{{ item.name }}/ && {{ item.requirements }}"
  become: yes
  when: item.requirements is defined
  loop: "{{ tools }}"

- name: Download subjs
  become: yes
  get_url:
    url: "https://github.com/lc/subjs/releases/download/v1.0.1/subjs_1.0.1_linux_amd64.tar.gz"
    dest: "/tmp/subjs_1.0.1_linux_amd64.tar.gz"

- name: Ensure subjs directory exists
  file:
    path: "/opt/tools/js_hunting/subjs"
    state: directory
  become: yes

- name: Extract subjs
  become: yes
  unarchive:
    src: "/tmp/subjs_1.0.1_linux_amd64.tar.gz"
    dest: "/opt/tools/js_hunting/subjs"
    remote_src: yes

- name: Copy subjs binary to /usr/local/bin
  become: yes
  copy:
    src: "/opt/tools/js_hunting/subjs/subjs"
    dest: "/usr/local/bin/subjs"
    mode: "0755"