- name: Install w3af
  ignore_errors: yes
  git:
    repo: 'https://github.com/andresriancho/w3af.git'
    dest: /opt/tools/frameworks/w3af
  become: yes

- name: Install Arachni
  ignore_errors: yes
  shell: |
    gem install bundler && \
    gem install arachni
  become: yes
