- name: Ensure cms_scanner directory exists
  ignore_errors: yes
  file:
    path: "/opt/tools/cms_scanner"
    state: directory
  become: yes

- name: Install Droopescan
  ignore_errors: yes
  shell: "pip3 install droopescan --break-system-packages"
  become: yes

- name: Download latest Nrich
  ignore_errors: yes
  become: yes
  shell: |
    LATEST_NRICH=$(curl -s https://gitlab.com/api/v4/projects/33695681/releases | jq -r '.[0].assets.links[0].url')
    wget $LATEST_NRICH -O /tmp/nrich_latest_amd64.deb

- name: Install Nrich
  ignore_errors: yes
  shell: dpkg -i /tmp/nrich_latest_amd64.deb
  become: yes

- name: Install AEM-Hacking using git
  ignore_errors: yes
  git:
    repo: 'https://github.com/0ang3el/aem-hacker.git'
    dest: /opt/tools/cms_scanner/aem-hacker
  become: yes

- name: Install requirements for AEM-Hacking
  ignore_errors: yes
  shell: "pip3 install -r /opt/tools/cms_scanner/aem-hacker/requirements.txt --break-system-packages"
  become: yes

- name: Install WhatWaf using git
  ignore_errors: yes
  git:
    repo: 'https://github.com/Ekultek/WhatWaf.git'
    dest: /opt/tools/cms_scanner/WhatWaf
  become: yes

- name: Copy WhatWaf binary to /usr/local/bin
  ignore_errors: yes
  copy:
    src: "/opt/tools/cms_scanner/WhatWaf/whatwaf"
    dest: "/usr/local/bin/whatwaf"
    mode: "0755"
  become: yes
