- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - apkleaks
    - aeroot
    - frida-tools
    - objection
    - radare2
    - dnspy

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - openjdk-11-jdk
    - python3.8
    - python3-dev
    - python3-venv
    - python3-pip
    - build-essential
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libjpeg62-turbo-dev
    - zlib1g-dev
    - wkhtmltopdf

- name: Clone Mobile-Security-Framework-MobSF from GitHub
  git:
    repo: https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
    dest: /opt/Mobile-Security-Framework-MobSF

- name: Run setup.sh
  command:
    cmd: ./setup.sh
    chdir: /opt/Mobile-Security-Framework-MobSF

- name: Install python2.7
  apt:
    name: python2.7
    state: latest

- name: Download get-pip.py for Python 2.7
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /usr/lib/python2.7/get-pip.py

- name: Install pip for Python 2.7
  command:
    cmd: python2.7 get-pip.py
    chdir: /usr/lib/python2.7

- name: Install prerequisites for Drozer
  command:
    cmd: pip2.7 install "{{ item }}"
  loop:
    - twisted
    - pyOpenSSL
    - protobuf

- name: Download Drozer wheel file
  get_url:
    url: https://github.com/FSecureLABS/drozer/releases/download/2.4.4/drozer-2.4.4-py2-none-any.whl
    dest: /tmp/drozer-2.4.4-py2-none-any.whl

- name: Install Drozer
  command:
    cmd: pip2.7 install /tmp/drozer-2.4.4-py2-none-any.whl

- name: Install additional tools
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apksigner
    - apktool
    - zipalign
    - adb
    - aapt
    - jadx
    - jadx-gui
    - jadx-cli
    - jadx-dex2jar

- name: Install OpenJDK headless for jarsigner
  apt:
    name: openjdk-11-jdk-headless
    state: latest
    