- name: Ensure ssti_tools directory exists
  ignore_errors: yes
  file:
    path: "/opt/tools/ssti_tools"
    state: directory
  become: yes


- name: Install tplmap using git
  ignore_errors: yes
  git:
    repo: 'https://github.com/epinna/tplmap.git'
    dest: /opt/tools/ssti_tools/tplmap
  become: yes

- name: Install requirements for tplmap in virtual environment
  ignore_errors: yes
  shell: "pip install -r /opt/tools/ssti_tools/tplmap/requirements.txt --break-system-packages"
  become: yes
  ignore_errors: yes
